name: CapsLimit
main: CapsLimit\CapsLimit
api: 4.0.0
version: 1.0.0
author: Ayrz, Ihsan48

commands:
  capslimit:
    description: Sets maximum caps can be used by player
    permission: capslimit.cmd

permissions:
  capslimit.cmd:
    description: Allow to use set default usage of maximum caps!
    default: op
